---

- name: Add MongoDB APT Key from KeyServer
  become: yes
  become_user: root
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927

- name: Add MongoDB to APT Sources
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/apt/sources.list.d/mongodb-org-3.2.list
    regexp: "^deb(\\s+)http://repo.mongodb.org/apt/"
    line: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

- name: "apt-get update"
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Install MongoDB
  become: yes
  become_user: root
  apt: name="mongodb-org" state=latest

- name: Register MongoDB as Service
  become: yes
  become_user: root
  copy:
    src: mongodb.service
    dest: /etc/systemd/system/mongodb.service
    owner: root
    group: root
    mode: 0644

- name: Restart MongoDB Service
  become: yes
  become_user: root
  service: name=mongodb state=restarted

- name: Enable MongoDB Service
  become: yes
  become_user: root
  service: name=mongodb enabled=yes
